name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Vagrant Version
        run: vagrant --version
        
      # Runs a single command using the runners shell
      - name: Vagrant Up
        run: vagrant up
        continue-on-error: true

      # Runs a single command using the runners shell
      - name: Vagrant Status
        run: vagrant status

      # Runs a single command using the runners shell
      - name: Vagrant Package
        run: vagrant package --vagrantfile ./Vagrantfile --output ggcore.box

      # Runs a single command using the runners shell
      - name: List files
        run: dir

      # Runs a single command using the runners shell
      - name: VBoxManage Export
        run: "&amp;" 'C:\Program Files\Oracle\VirtualBox\VBoxManage.exe' export ggcore -o ggcore.ova
        continue-on-error: true

      # Runs a single command using the runners shell
      - name: Vagrant Destroy
        run: vagrant destroy --force
