name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Vagrant Up
        run: vagrant up
        continue-on-error: true

      - name: Vagrant Package BOX
        run: vagrant package --vagrantfile ./Vagrantfile --output ggcore.box

      - name: VBoxManage Export OVA
        run: |
          $VMS=& 'C:\Program Files\Oracle\VirtualBox\VBoxManage.exe' list vms
          $HELPER=$VMS.IndexOf(" ")
          $VMNAME=echo $VMS.Substring(0+1,$HELPER-2)
          & 'C:\Program Files\Oracle\VirtualBox\VBoxManage.exe' export $VMNAME -o ggcore.ova
        continue-on-error: true

      - name: Vagrant Destroy
        run: vagrant destroy --force
